// Code generated by Slice Machine. DO NOT EDIT.

import Speakers from './Speakers/index.svelte';
import Weloveweblink from './Weloveweblink/index.svelte';
import Workshops from './Workshops/index.svelte';

export const components = {
	speakers: Speakers,
	weloveweblink: Weloveweblink,
	workshops: Workshops
};
