// Code generated by Slice Machine. DO NOT EDIT.

import Speakers from './Speakers/index.svelte';
import Workshops from './Workshops/index.svelte';

export const components = {
	speakers: Speakers,
	workshops: Workshops
};
